language: python
python:
 - 3.6

install:
  - pip install -r requirements.txt

script:
  - cd tests
  - python test_all.py
  - cd ../chess
  - coverage run main.py

after_success:
  - pip install python-coveralls
  - coveralls