language: python
python:
 - "3.6"

install:
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - tox
  - cd tests
  - coverage test_all.py

after_success:
  - pip install python-coveralls
  - coveralls